StratosphereLabs/flight-logger

app/routes/users.ts
package-lock.json
package.json
resources/blocks/FlightsCard.tsx
resources/blocks/MapCard.tsx
resources/blocks/ProfileCard.tsx
resources/common/components/Form.tsx
resources/common/components/Table.tsx
resources/index.tsx

- Fix missing flight number appearing as null #30 
- Fix stale data on login, add react query devtools #34

Private beta 1 bugfixes

---

package-lock.json
package.json
resources/__tests__/__snapshots__/App.test.tsx.snap
resources/blocks/MapCard.tsx
resources/common/components/FormControl.tsx
resources/common/components/FormLabel.tsx
resources/common/components/FormRadio.tsx
resources/common/components/HeaderSortIcon.tsx
resources/common/components/Icons.tsx
resources/common/components/Table.tsx
resources/common/components/TypeaheadInput.tsx
resources/common/hooks/useTypeaheadInput.ts
resources/common/types.ts
resources/pages/AddFlight/AddFlight.tsx
resources/pages/AddFlight/AircraftTypeInput.tsx
resources/pages/AddFlight/AirlineInput.tsx
resources/pages/AddFlight/ArrivalAirportInput.tsx
resources/pages/AddFlight/DepartureAirportInput.tsx
resources/pages/ForgotPassword/ForgotPassword.tsx
resources/pages/Login/LoginForm.tsx
resources/pages/Register/RegisterForm.tsx
resources/pages/ResetPassword/ResetPassword.tsx

Added keyboard accessibility to typeahead dropdowns

---

package-lock.json
package.json
resources/common/components/FormLabel.tsx
resources/common/components/TypeaheadInput.tsx
resources/layouts/MainLayout/MainNavbar.tsx

Fixes #39 
- Clear selected value in typeahead input when form is reset

39 clear typeahead input when value is reset

---

resources/blocks/FlightsCard.tsx
resources/common/components/Modal.tsx
resources/common/components/TypeaheadInput.tsx
resources/pages/AddFlight/AddFlight.tsx
resources/pages/AddFlight/DepartureAirportInput.tsx

Fixes #44 
- Added keyboard accessibility to common modal component
- Added code to remove flight from flights list when delete is successful

44 remove flight from list programmatically instead of refetching data

---

resources/common/components/TypeaheadInput.tsx
resources/pages/AddFlight/AddFlight.tsx
resources/pages/AddFlight/DepartureAirportInput.tsx

- Changed forwardRef to inputRef prop in typeahead component

Fix typescript issues

---

app/parsers/flightdiary.ts
app/routes/users.ts
app/utils/datetime.ts
app/utils/flightdiary.ts
package-lock.json
package.json
prisma/migrations/20221214225156_added_duration_column/migration.sql
prisma/schema.prisma
resources/blocks/FlightsCard.tsx
resources/common/components/Icons.tsx

48 add duration column to flights in database

---

package-lock.json
package.json
resources/__tests__/__snapshots__/App.test.tsx.snap
resources/common/hooks/index.ts
resources/common/hooks/useCopyToClipboard.ts
resources/pages/Home/CreateItineraryModal.tsx
resources/pages/Itineraries/Itineraries.tsx
resources/pages/Itinerary/Itinerary.tsx

- Fixed issue with airport fields not resetting after adding an itinerary
- Added `useCopyToClipboard` hook
- Added copy link button on itinerary page

Fixed bugs

---

app/routes/flights.ts
app/routes/users.ts
app/utils/datetime.ts
app/utils/trips.ts
resources/common/components/UserFlightsTable.tsx
resources/pages/AddFlight/AddFlight.tsx
resources/pages/Flights/Flights.tsx
resources/pages/Trips/TripDisclosure.tsx
resources/pages/Trips/Trips.tsx

- Fixed bug with missing tripId when adding a flight
- FIxed trips in wrong order under trips tab
- Fixed seat number field width in add flight page
- Improved Trips page styling and added sections for upcoming and completed trips
- Tweaked date badge colors in flights table

Fixed bugs, improved trips page

---

app/db/seeders/seedAirframes.ts
app/routes/users.ts
app/schemas/users.ts
app/utils/flights.ts
app/utils/trips.ts
resources/common/components/SearchButton.tsx
resources/common/components/UserFlightsTable.tsx
resources/pages/AddFlight/AddFlight.tsx
resources/pages/Flights/DeleteFlightModal.tsx
resources/pages/Flights/EditFlightModal.tsx
resources/pages/Flights/Flights.tsx
resources/pages/Flights/flightsPageStore.ts
resources/pages/Home/CreateItineraryModal.tsx
resources/pages/Home/ItineraryBuilderFields.tsx
resources/pages/Itineraries/DeleteItineraryModal.tsx
resources/pages/Itineraries/Itineraries.tsx
resources/pages/Itinerary/Itinerary.tsx
resources/pages/Profile/MapCard.tsx
resources/pages/Trips/DeleteTripModal.tsx
resources/pages/Trips/TripDisclosure.tsx
resources/pages/Trips/Trips.tsx
resources/pages/Trips/tripsPageStore.ts

- Changed order of upcoming flights on user flights page from descending to ascending
- Changed order of upcoming trips on user flights page from descending to ascending
- Added "Current Flight" section to user flights page

Fixed flights and trips order

---

app/routes/users.ts
resources/common/hooks/index.ts
resources/common/hooks/useProfilePage.ts
resources/layouts/MainLayout/ProfileLayout.tsx
resources/pages/Flights/Flights.tsx
resources/pages/Itineraries/Itineraries.tsx
resources/pages/Profile/CompletedFlights.tsx
resources/pages/Profile/CurrentFlightCard.tsx
resources/pages/Profile/MapCard.tsx
resources/pages/Profile/ProfileCard.tsx
resources/pages/Profile/UpcomingFlights.tsx
resources/pages/Trips/Trips.tsx

- Fixed UNAUTHORIZED error when navigating to profile while not logged in
- Added city names to current flight info card on profile page

Fixed auth errors, tweaked current flight card

---

app/commands/flightRadar/fetchRegistrationData.ts
app/commands/flightRadar/types.ts
app/commands/flightRadar/updateFlightRegistrations.ts
app/db/seeders/seedAirframes.ts
app/routes/users.ts

- Fetch aircraft type when scraping flight information and automatically update flights.
- Search and connect aircraft types while seeding airframes

Aircraft type data improvements

---

app/commands/flightAware/updateFlightTimes.ts
app/commands/flightStats/types.ts
app/commands/updateData.ts
app/db/seeders/index.ts
app/db/seeders/seedAircraftTypes.ts
app/db/seeders/seedAirlines.ts
app/db/seeders/seedAirports.ts
app/db/seeders/seedManufacturers.ts
app/routes/users.ts
app/utils/datetime.ts
resources/common/components/UserFlightsTable.tsx
resources/pages/Flights/ViewFlightModal.tsx
resources/pages/Profile/CompletedFlights.tsx
resources/pages/Profile/CurrentFlightCard.tsx
resources/pages/Profile/MapCard.tsx
resources/pages/Profile/ProfileCard.tsx
resources/pages/Profile/UpcomingFlights.tsx

- Fixed bugs with live flight card showing incorrect flight times
- Added days added indicator as superscript to all arrival times where applicable
- Added seeders for manufacturers, airlines, aircraft, and airports to automatic updater.

Fix flight time bugs, added days added indicator to all arrival times

---

resources/pages/Profile/CompletedFlights.tsx
resources/pages/Profile/CurrentFlightCard.tsx
resources/pages/Profile/MapCard.tsx
resources/pages/Profile/UpcomingFlights.tsx

- Remove gap between aircraft and tail number in mobile mode
- Fixed alignment of aircraft icon and progress bar in mobile mode
- Added shadow-md to recent and upcoming flights tables

Fixed styling issues

---

app/routes/users.ts
app/utils/datetime.ts
app/utils/distance.ts
resources/__tests__/__snapshots__/App.test.tsx.snap
resources/pages/Profile/CurrentFlightCard.tsx
resources/pages/Profile/MapCard.tsx

- Added estimated runway arrival to current flight card
- Added duration timestamps next to departure and arrival times in current flight card
- Improved flight location estimation on map, center on aircraft when loaded

Improved flight location accuracy, added runway arrival estimate

---

app/commands/updateData.ts
app/data/flightRadar/fetchFlightRegistrationData.ts
resources/pages/Profile/CurrentFlightCard.tsx
resources/pages/Profile/constants.ts

- Fixed issue with flight times scraper not scraping delayed times
- Added border to current flight card, fix duration text alignment
- Added new job that runs every 5 minutes to update flights that are arriving within two hours

More live flight improvements

---

app/commands/updateFlightRegistrationData.ts
app/commands/updateFlightTimesData.ts
app/data/flightRadar/fetchFlightRegistrationData.ts
app/data/flightStats/constants.ts
app/data/flightStats/fetchFlightStatsData.ts
app/data/flightStats/types.ts
app/db/seeders/seedAirlines.ts
app/routes/flightData.ts
app/utils/flights.ts
prisma/migrations/20240130223935_make_iata_column_optional_in_airlines_table/migration.sql
prisma/schema.prisma
resources/common/components/AirlineInput.tsx
resources/pages/AddFlight/AddFlight.tsx
resources/pages/CreateItinerary/ItineraryBuilderFields.tsx
resources/pages/Flights/EditFlightModal.tsx
resources/pages/Itinerary/Itinerary.tsx
resources/pages/Profile/AddFlightForm.tsx
resources/pages/Profile/CurrentFlightCard.tsx
resources/pages/Profile/FlightsTable.tsx

- Added retry mechanism to flight times and flight registration fetching functions
- Added 500 more airlines to the database (with missing IATA codes)

Added airlines without IATA code to database, data fetching improvements

---

app/routes/statistics.ts
app/schemas/statistics.ts
app/utils/datetime.ts
package-lock.json
package.json
resources/layouts/MainLayout/MainLayout.tsx
resources/pages/Profile/Profile.tsx
resources/pages/Profile/components/RecentFlights/FlightsTable.tsx
resources/pages/Profile/components/Statistics/ReasonRadarChart.tsx
resources/pages/Profile/components/Statistics/SeatPositionRadarChart.tsx
resources/pages/Profile/components/Statistics/Statistics.tsx
resources/pages/Profile/components/Statistics/TopAircraftTypesChart.tsx
resources/pages/Profile/components/Statistics/TopAirlinesChart.tsx
resources/pages/Profile/components/Statistics/TopAirportsChart.tsx
resources/pages/Profile/components/Statistics/TopRoutesChart.tsx
resources/pages/Profile/components/Statistics/constants.ts
tailwind.config.cjs

- Improved responsiveness of Profile page
- Added radar charts for seat position and flight reason

Profile page improvements

---

resources/pages/Profile/components/Statistics/FlightClassRadarChart.tsx
resources/pages/Profile/components/Statistics/FlightTypePieChart.tsx
resources/pages/Profile/components/Statistics/ReasonRadarChart.tsx
resources/pages/Profile/components/Statistics/SeatPositionRadarChart.tsx

- Fixed text truncation when hovering over pie slices and adjusted size and animations.
- Adjusted margins for all charts.

Fix flight type chart styling

---

resources/index.css
resources/layouts/AuthenticationLayout/AuthenticationLayout.tsx
resources/layouts/MainLayout/MainLayout.tsx
resources/pages/Home/WelcomeHero.tsx
resources/pages/Profile/components/Map/MapCard.tsx
resources/pages/Profile/components/Map/ProfileOverlay.tsx

- Removed blue box around map when map element is focused
- Fixed missing footer in mobile
- Added "Register" button to login page
- Changed "Get Started" button in Home page to redirect to either Login page or Profile home.
- Fixed profile overlay styling

Styling fixes in mobile mode

---

app/routes/flightData.ts
app/routes/users.ts
prisma/migrations/20240406013551_added_notifications_table/migration.sql
prisma/migrations/20240503021209_added_added_by_user_id_column_to_flights_table/migration.sql
prisma/schema.prisma
resources/pages/Flights/DeleteFlightModal.tsx
resources/pages/Profile/components/Flights/AddFlightForm.tsx
resources/pages/Profile/components/Flights/CurrentFlightCard.tsx
resources/pages/Profile/components/Flights/FlightsCard.tsx

- Added `addedByUserId` column to `flights` table.
- Fixed prisma schema being out of sync

Added ability to add flights directly from other profiles

---

app/data/flightAware/fetchFlightAwareData.ts
app/data/flightRadar/fetchFlightRadarData.ts
app/data/types.ts
app/routes/flightData.ts
app/schemas/flightData.ts
resources/pages/Profile/components/Flights/AddFlightForm.tsx

- Added ability to search and add flights up to one week in the future

Expanded date range for search by flight number

---

resources/common/components/AirportLabelOverlay.tsx
resources/layouts/MainLayout/ProfileFiltersForm.tsx
resources/pages/Home/FollowingMap.tsx
resources/pages/Profile/components/Flights/ActiveFlightCard.tsx
resources/pages/Profile/components/Map/GoogleMap.tsx

- Made profile filter menus larger for easier access on mobile
- Added fractional zoom to all maps for better control over zoom
- Tweaked z-indexes of all map overlays

Small map improvements

---

app/data/flightRadar/fetchFlightRadarData.ts
app/data/flightRadar/types.ts
app/routes/aircraftTypes.ts
app/routes/airlines.ts
app/routes/airports.ts
app/routes/flightData.ts
app/schemas/flightData.ts
package-lock.json
package.json
resources/common/components/AirlineInput.tsx
resources/pages/AddFlight/AddFlight.tsx
resources/pages/Flights/EditFlightModal.tsx
resources/pages/Home/FollowingMap.tsx
resources/pages/Profile/components/Flights/AddFlightForm.tsx
resources/pages/Profile/components/Flights/constants.ts

- Improved typeahead search responses for airlines, airports, and aircraft types
- Added airline logos to typeahead search
- Added function to scrape flights data given a departure date and route

Improved data search results

---

app/routes/airports.ts
app/routes/flights.ts
app/routes/statistics.ts
app/schemas/airports.ts
app/schemas/statistics.ts
app/schemas/users.ts
resources/pages/AddFlight/AddFlight.tsx
resources/pages/Flights/Flights.tsx
resources/pages/Home/FollowingMap.tsx
resources/pages/Profile/Profile.tsx
resources/pages/Profile/components/Flights/ActiveFlightCard.tsx
resources/pages/Profile/components/Flights/AddFlightForm.tsx
resources/pages/Profile/components/Flights/FlightsCard.tsx
resources/pages/Profile/components/Map/CesiumMap.tsx
resources/pages/Profile/components/Map/GoogleMap.tsx
resources/pages/Profile/components/Map/MapCard.tsx
resources/pages/Profile/components/Map/ProfileOverlay.tsx

- Added ability to filter flights in list when selecting airport on map (following map, profile map)
- Removed unneeded queries for fetching flight count data
- Other refactoring and code cleanup

Added airport selection filter on map

---

package-lock.json
package.json
resources/common/components/FlightChangelogTable.tsx
resources/common/components/Icons.tsx
resources/common/components/SearchButton.tsx
resources/common/components/ThemeButton.tsx
resources/layouts/MainLayout/MainNavbar.tsx
resources/pages/Home/FlightRow.tsx
resources/pages/Home/FollowingMap.tsx
resources/pages/Profile/Profile.tsx
resources/pages/Profile/components/Flights/ActiveFlightCard.tsx
resources/pages/Profile/components/Flights/AddFlightForm.tsx
resources/pages/Profile/components/Flights/FlightsCard.tsx
resources/pages/Profile/components/Map/MapCard.tsx
resources/pages/Profile/components/Map/ProfileOverlay.tsx

- Fixed close button positioning on active flight card
- Added button titles to all icon buttons
- Replaced plus icon on add flight buttons with new airplane plus icon
- Made icons inside dropdowns larger
- Increased size of airport codes and city names on active flight card and homepage following flights list.
- Removed box shadow while hovering on flight cards
- Removed "Scheduled", "Arrived", and "En Route" headers from homepage following flights list.

Styling improvements

---

app/routes/statistics.ts
app/utils/datetime.ts
resources/pages/Profile/components/Statistics/TotalsChart.tsx

- Added days count to duration total section
- Added kilometers count to distance total section
- Tweaked opacity of icons
- Fixed total distance calculation with diverted flights

Added secondary units to totals section, other tweaks

---

app/routes/flights.ts
app/routes/statistics.ts
app/schemas/flights.ts
app/utils/flights.ts
resources/common/components/Icons.tsx
resources/layouts/MainLayout/MainNavbar.tsx
resources/layouts/MainLayout/ProfileFiltersForm.tsx
resources/layouts/MainLayout/ProfileFiltersModal.tsx
resources/pages/Flights/Flights.tsx
resources/pages/Profile/components/Flights/FlightsCard.tsx
resources/pages/Profile/components/Flights/FlightsTable.tsx
resources/pages/Profile/components/Flights/FlightsTableBasic.tsx
resources/pages/Profile/components/Map/GoogleMap.tsx
resources/pages/Profile/components/Map/MapCard.tsx
resources/pages/Profile/components/Statistics/FlightClassRadarChart.tsx
resources/pages/Profile/components/Statistics/FlightLengthRadarChart.tsx
resources/pages/Profile/components/Statistics/FlightTypePieChart.tsx
resources/pages/Profile/components/Statistics/ReasonRadarChart.tsx
resources/pages/Profile/components/Statistics/SeatPositionRadarChart.tsx
resources/pages/Profile/components/Statistics/TopAircraftTypesChart.tsx
resources/pages/Profile/components/Statistics/TopAirlinesChart.tsx
resources/pages/Profile/components/Statistics/TopAirportsChart.tsx
resources/pages/Profile/components/Statistics/TopCountriesChart.tsx
resources/pages/Profile/components/Statistics/TopRoutesChart.tsx
resources/pages/Profile/components/Statistics/TotalsChart.tsx
resources/pages/Profile/hooks/useProfileFilterForm.ts

- Moved flights search input from top of flights table to left side of filters toolbar.
- Added modal button and created modal to adjust filters in mobile mode
- Added filters to statistics card to use flight search query to filter data

Moved flights search input to filters toolbar, redesigned filters interface

---

app/data/flightRadar/fetchFlightRadarData.ts
app/data/types.ts
app/routes/flightData.ts
app/routes/users.ts
app/utils/flights.ts
resources/common/components/UserFlightsTable.tsx
resources/common/components/UserInput.tsx
resources/pages/Flights/ViewFlightModal.tsx
resources/pages/Home/FlightRow.tsx
resources/pages/Profile/components/Flights/ActiveFlightCard.tsx
resources/pages/Profile/components/Flights/AddFlightForm.tsx
resources/pages/Profile/components/Flights/UserSelectModal.tsx

- Fixed order of flight search results
- Made table contents larger in desktop mode
- Moved logic for determining airport municipality strings to server side

Flight search table improvements

---

app/commands/index.ts
app/commands/updateData.ts
app/commands/updateFlightData.ts
app/commands/updateFlightRegistrationData.ts
app/commands/updateFlightTimesData.ts
app/commands/updateFlightTrackData.ts
app/commands/updateFlightWeatherReports.ts
app/commands/updateOnTimePerformanceData.ts
app/routes/flightData.ts
app/routes/flights.ts
app/utils/flights.ts
app/utils/weather.ts

- Refactored code for flight updates
- Improved log messages

Fixed logging in update method

---

app/utils/flights.ts
resources/common/mapStyle.ts
resources/pages/Flight/Flight.tsx
resources/pages/Home/FollowingMap.tsx

- Fixed incorrect color in projected path
- Made airports, taxiways, and runways visible
- Fixed tracking text on aircraft labels

Improved ground tracking

---

app/utils/flights.ts
resources/common/components/AirportLabelOverlay.tsx
resources/pages/Flight/Flight.tsx

- Added distance in miles to airport labels on Flight page
- Fixed altitude change icon showing minor changes in altitude during cruise

Added distance to airport in airport labels while flight is en route
